import type { DeploymentProfile, ProductionRisk, ReadinessCheck } from "./types.ts";

export const defaultDeploymentProfiles: DeploymentProfile[] = [
  {
    id: "local",
    name: "local",
    description: "Default developer profile: in-memory state, mock providers, demo/API dashboard, no external calls.",
    requiredComponents: ["api", "web", "worker"],
    requiredEnvVars: [],
    disabledFeatures: [
      "remote_git_by_default",
      "remote_llm_by_default",
      "real_mcp_transport",
      "production_auth",
      "real_secret_backend",
      "vendor_cli_execution",
      "production_deployment"
    ],
    allowedProviderKinds: ["mock", "local_fixture"],
    storageMode: "in_memory",
    authMode: "mock",
    secretMode: "metadata_only_env_optional",
    policyMode: "static_typescript",
    observabilityMode: "local_logs_only",
    readinessChecks: ["local_mock_first_pass", "local_in_memory_warning", "local_no_external_calls_pass"],
    metadata: { productionTrafficAllowed: false, mockFirst: true }
  },
  {
    id: "integration",
    name: "integration",
    description: "Optional integration profile for gated GitHub/OpenAI-compatible/Postgres tests without production traffic.",
    requiredComponents: ["api", "web", "worker", "migration-job"],
    requiredEnvVars: [],
    disabledFeatures: [
      "production_auth",
      "real_secret_backend",
      "auto_merge",
      "real_mcp_transport",
      "vendor_cli_execution",
      "production_deployment"
    ],
    allowedProviderKinds: ["mock", "github_gated", "openai_compatible_gated", "local_fixture"],
    storageMode: "postgres_optional",
    authMode: "mock",
    secretMode: "secretref_env",
    policyMode: "static_typescript",
    observabilityMode: "local_logs_only",
    readinessChecks: ["integration_gates_pass", "integration_mock_auth_warning", "integration_postgres_optional_warning"],
    metadata: { productionTrafficAllowed: false, integrationTestsGated: true }
  },
  {
    id: "staging",
    name: "staging",
    description: "Pre-production rehearsal target. Current repository only defines required blockers; it does not implement staging deployment.",
    requiredComponents: ["api", "web", "worker", "migration-job", "background-job"],
    requiredEnvVars: ["AICHESTRA_STORAGE_PROVIDER", "AICHESTRA_DATABASE_URL"],
    disabledFeatures: ["auto_merge", "vendor_cli_execution", "real_mcp_transport_until_allowlisted"],
    allowedProviderKinds: ["mock", "github_gated", "openai_compatible_gated"],
    storageMode: "postgres_required",
    authMode: "future_oidc_saml",
    secretMode: "real_secret_backend_required",
    policyMode: "managed_bundle_required",
    observabilityMode: "required_external_stack",
    readinessChecks: [
      "staging_postgres_required",
      "staging_migration_runner_required",
      "staging_real_auth_required",
      "staging_secret_backend_required",
      "staging_audit_retention_required"
    ],
    metadata: { productionTrafficAllowed: false, rehearsalOnly: true }
  },
  {
    id: "production",
    name: "production",
    description: "Target production profile. This is a planning model only and is blocked until required controls are implemented.",
    requiredComponents: ["api", "web", "worker", "migration-job", "background-job", "local-agent"],
    requiredEnvVars: ["AICHESTRA_STORAGE_PROVIDER", "AICHESTRA_DATABASE_URL"],
    disabledFeatures: ["mock_actor", "legacy_env_credentials", "auto_merge", "unsafe_default_providers", "vendor_cli_credential_cache_read"],
    allowedProviderKinds: ["github_app_future", "openai_compatible_gated", "mcp_allowlisted_future", "local_agent_governed_future"],
    storageMode: "postgres_required",
    authMode: "production_required",
    secretMode: "real_secret_backend_required",
    policyMode: "managed_bundle_required",
    observabilityMode: "required_external_stack",
    readinessChecks: [
      "production_postgres_required",
      "production_auth_required",
      "production_secret_backend_required",
      "production_policy_bundle_required",
      "production_observability_required",
      "production_audit_retention_required",
      "production_backup_restore_required",
      "production_tenant_isolation_required",
      "production_mock_actor_disabled_required",
      "production_no_env_fallback_required",
      "production_no_unsafe_default_providers_required"
    ],
    metadata: { productionTrafficAllowed: false, productionReady: false }
  }
];

export const defaultReadinessChecks: ReadinessCheck[] = [
  {
    id: "local_mock_first_pass",
    profileId: "local",
    category: "runtime",
    name: "Mock-first local runtime",
    status: "pass",
    severity: "low",
    description: "Local profile defaults to mock providers and in-memory state.",
    remediation: "Keep local defaults mock-first.",
    evidence: ["README.md", "AGENTS.md", "docs/audits/2026-05-11-phase-progress-audit.md"],
    metadata: { externalCalls: false }
  },
  {
    id: "local_in_memory_warning",
    profileId: "local",
    category: "database",
    name: "In-memory state is not production persistence",
    status: "warning",
    severity: "medium",
    description: "The default store is intentionally in-memory.",
    remediation: "Use Postgres with migrations and backups before staging or production.",
    evidence: ["docs/features/persistent-db/v1.md"],
    metadata: { productionBlocker: true }
  },
  {
    id: "local_no_external_calls_pass",
    profileId: "local",
    category: "integration",
    name: "Default runtime avoids external calls",
    status: "pass",
    severity: "low",
    description: "Default tests and runtime do not call real providers.",
    remediation: "Keep integration tests behind explicit gates.",
    evidence: ["docs/audits/2026-05-11-phase-progress-audit.md"],
    metadata: { mockFirst: true }
  },
  {
    id: "integration_gates_pass",
    profileId: "integration",
    category: "integration",
    name: "Real provider paths remain gated",
    status: "pass",
    severity: "medium",
    description: "GitHub and OpenAI-compatible paths require explicit env gates and allowlists.",
    remediation: "Continue requiring operation-specific gates and integration-test env flags.",
    evidence: ["docs/features/real-git-adapter/v2.md", "docs/features/llm-gateway/v2.md"],
    metadata: { productionTrafficAllowed: false }
  },
  {
    id: "integration_mock_auth_warning",
    profileId: "integration",
    category: "identity",
    name: "Integration profile still uses mock auth",
    status: "warning",
    severity: "high",
    description: "Integration testing can use mock actors, but this cannot be promoted to production.",
    remediation: "Implement production IdP and request auth middleware before staging/production.",
    evidence: ["docs/foundations/auth-rbac/v0.md"],
    metadata: { mockActorAllowed: true }
  },
  {
    id: "integration_postgres_optional_warning",
    profileId: "integration",
    category: "database",
    name: "Postgres is optional in integration",
    status: "warning",
    severity: "medium",
    description: "Postgres contract tests are optional unless AICHESTRA_TEST_DATABASE_URL is set.",
    remediation: "Make Postgres mandatory in staging.",
    evidence: ["docs/features/persistent-db/v1.md"],
    metadata: { postgresRequired: false }
  },
  {
    id: "staging_postgres_required",
    profileId: "staging",
    category: "database",
    name: "Staging requires Postgres",
    status: "fail",
    severity: "high",
    description: "Staging must not run on in-memory repositories.",
    remediation: "Require AICHESTRA_STORAGE_PROVIDER=postgres, AICHESTRA_DATABASE_URL, migration job, and repository contract validation.",
    evidence: ["docs/features/persistent-db/v1.md"],
    metadata: { requiredBeforeStaging: true }
  },
  {
    id: "staging_migration_runner_required",
    profileId: "staging",
    category: "database",
    name: "Migration runner is not operationalized",
    status: "fail",
    severity: "high",
    description: "Migrations are explicit scripts but not wrapped in a release process.",
    remediation: "Define migration job ordering, rollback, backup, and restore rehearsal.",
    evidence: ["scripts/db/migrate.mjs"],
    metadata: { deploymentImplementation: false }
  },
  {
    id: "staging_real_auth_required",
    profileId: "staging",
    category: "identity",
    name: "Production auth provider is missing",
    status: "fail",
    severity: "critical",
    description: "Only MockAuthProvider and disabled future provider placeholders exist.",
    remediation: "Implement OIDC/SAML request authentication, SCIM/team sync planning, and tenant-aware authorization.",
    evidence: ["docs/foundations/auth-rbac/v0.md"],
    metadata: { productionAuthEnabled: false }
  },
  {
    id: "staging_secret_backend_required",
    profileId: "staging",
    category: "secrets",
    name: "Real secret backend is missing",
    status: "fail",
    severity: "critical",
    description: "SecretRef-backed credentials currently use an explicit env provider only.",
    remediation: "Add a real secret backend behind SecretManager before staging.",
    evidence: ["docs/foundations/secretref-provider-credentials/v1.md", "docs/features/secrets-sandbox/v0.md"],
    metadata: { envProviderOnly: true }
  },
  {
    id: "staging_audit_retention_required",
    profileId: "staging",
    category: "audit",
    name: "Audit retention is not configured",
    status: "fail",
    severity: "high",
    description: "Audit repositories are mostly in-memory and no retention/export process exists.",
    remediation: "Define durable audit stores, retention classes, export jobs, and redaction checks.",
    evidence: ["docs/foundations/repository-inventory.md"],
    metadata: { auditExportConfigured: false }
  },
  {
    id: "production_postgres_required",
    profileId: "production",
    category: "database",
    name: "Production Postgres and migrations required",
    status: "fail",
    severity: "critical",
    description: "Production requires durable storage, migration governance, indexes, backups, and restore testing.",
    remediation: "Promote Postgres from opt-in to required for production profile and add operational migration controls.",
    evidence: ["docs/features/persistent-db/v1.md", "docs/foundations/persistent-storage-schema-v0.md"],
    metadata: { productionBlocker: true }
  },
  {
    id: "production_auth_required",
    profileId: "production",
    category: "identity",
    name: "Production Auth/RBAC required",
    status: "fail",
    severity: "critical",
    description: "Mock auth is not production authentication.",
    remediation: "Implement production OIDC/SAML and service-account authentication with tenant/team scoping.",
    evidence: ["docs/foundations/auth-rbac/v0.md"],
    metadata: { productionBlocker: true }
  },
  {
    id: "production_secret_backend_required",
    profileId: "production",
    category: "secrets",
    name: "Production secret backend required",
    status: "fail",
    severity: "critical",
    description: "Env SecretRef provider is not sufficient for production secret management.",
    remediation: "Implement Vault or cloud secret manager integration behind existing SecretManager boundaries.",
    evidence: ["docs/features/secrets-sandbox/v0.md"],
    metadata: { productionBlocker: true }
  },
  {
    id: "production_policy_bundle_required",
    profileId: "production",
    category: "policy",
    name: "Managed policy bundles required",
    status: "fail",
    severity: "high",
    description: "Policy rules are static TypeScript defaults and cannot yet be reviewed, signed, versioned, or rolled back as bundles.",
    remediation: "Add a reviewed policy bundle workflow before production.",
    evidence: ["docs/features/policy-as-code/v0.md"],
    metadata: { productionBlocker: true }
  },
  {
    id: "production_observability_required",
    profileId: "production",
    category: "observability",
    name: "Observability stack required",
    status: "fail",
    severity: "high",
    description: "No production logging, metrics, tracing, alerting, or SLO backend is wired.",
    remediation: "Implement structured logs, metrics, traces, dashboards, and alerts.",
    evidence: ["docs/features/dashboard/v0.md"],
    metadata: { productionBlocker: true }
  },
  {
    id: "production_audit_retention_required",
    profileId: "production",
    category: "audit",
    name: "Audit retention and export required",
    status: "fail",
    severity: "high",
    description: "Compliance-grade audit retention and export are not implemented.",
    remediation: "Persist audit events, define retention classes, and add export controls.",
    evidence: ["docs/foundations/repository-inventory.md"],
    metadata: { productionBlocker: true }
  },
  {
    id: "production_backup_restore_required",
    profileId: "production",
    category: "database",
    name: "Backup and restore required",
    status: "fail",
    severity: "high",
    description: "No backup, restore test, or recovery objective process exists.",
    remediation: "Define backup schedule, restore drills, RPO/RTO, and migration rollback playbooks.",
    evidence: ["docs/features/persistent-db/v1.md"],
    metadata: { productionBlocker: true }
  },
  {
    id: "production_tenant_isolation_required",
    profileId: "production",
    category: "tenancy",
    name: "Tenant isolation required",
    status: "fail",
    severity: "critical",
    description: "Current read models and repositories are not production tenant scoped.",
    remediation: "Add tenant/org ids to request context, repository filters, audit, dashboard, and policy subjects.",
    evidence: ["docs/features/dashboard/v0.md", "docs/foundations/auth-rbac/v0.md"],
    metadata: { productionBlocker: true }
  },
  {
    id: "production_mock_actor_disabled_required",
    profileId: "production",
    category: "identity",
    name: "Mock actor must be disabled",
    status: "fail",
    severity: "critical",
    description: "Header-selected mock actors and MockAuthProvider are local/test-only.",
    remediation: "Reject mock actor modes in production profile after real auth exists.",
    evidence: ["docs/foundations/auth-rbac/v0.md"],
    metadata: { productionBlocker: true }
  },
  {
    id: "production_no_env_fallback_required",
    profileId: "production",
    category: "secrets",
    name: "Legacy env credential fallback must be disabled",
    status: "fail",
    severity: "high",
    description: "Legacy env fallback remains for compatibility when no SecretRef is configured.",
    remediation: "Add production profile validation that requires SecretRef plus real secret backend and blocks legacy env credentials.",
    evidence: ["docs/foundations/secretref-provider-credentials/v1.md"],
    metadata: { productionBlocker: true }
  },
  {
    id: "production_no_unsafe_default_providers_required",
    profileId: "production",
    category: "integration",
    name: "Unsafe default providers must be blocked",
    status: "fail",
    severity: "high",
    description: "Mock/default provider modes are local-safe but not production deployment controls.",
    remediation: "Add production profile boot validation for provider allowlists, MCP server allowlists, and disabled vendor CLI defaults.",
    evidence: ["docs/features/mcp-gateway/v0.md", "docs/features/llm-gateway/v2.md", "docs/features/real-git-adapter/v2.md"],
    metadata: { productionBlocker: true }
  }
];

export const defaultProductionRisks: ProductionRisk[] = [
  {
    id: "risk_mock_auth_in_production",
    category: "identity",
    title: "Mock auth accidentally promoted",
    severity: "critical",
    likelihood: "medium",
    impact: "Request attribution, RBAC, and audit evidence would not be trustworthy.",
    mitigation: "Implement production IdP integration and production profile boot-time rejection of mock auth.",
    owner: "platform-security",
    status: "open",
    metadata: { blocksProduction: true }
  },
  {
    id: "risk_env_secret_provider",
    category: "secrets",
    title: "Env SecretRef provider is insufficient for production",
    severity: "critical",
    likelihood: "high",
    impact: "Secret rotation, audit, leasing, and central revocation cannot be enforced.",
    mitigation: "Move SecretRef providers to Vault or a cloud secret manager before production.",
    owner: "platform-security",
    status: "open",
    metadata: { blocksProduction: true }
  },
  {
    id: "risk_in_memory_repositories",
    category: "database",
    title: "In-memory repositories lose operational state",
    severity: "high",
    likelihood: "high",
    impact: "Task, audit, policy, Local Agent, MCP, and governance records may be lost across restarts.",
    mitigation: "Finish durable repositories for every production-required store and mandate Postgres in staging/production.",
    owner: "platform",
    status: "open",
    metadata: { blocksProduction: true }
  },
  {
    id: "risk_static_policy_rules",
    category: "policy",
    title: "Static policy rules lack production change control",
    severity: "high",
    likelihood: "medium",
    impact: "Policy changes cannot be independently reviewed, signed, promoted, or rolled back.",
    mitigation: "Adopt signed policy bundles with tests and rollout/rollback controls.",
    owner: "platform-security",
    status: "open",
    metadata: { blocksProduction: true }
  },
  {
    id: "risk_no_observability_stack",
    category: "observability",
    title: "No production observability backend",
    severity: "high",
    likelihood: "high",
    impact: "Provider failures, policy denials, queue stalls, and credential issues may be invisible.",
    mitigation: "Add structured logs, metrics, traces, SLOs, dashboards, and alerts.",
    owner: "platform-ops",
    status: "open",
    metadata: { blocksProduction: true }
  },
  {
    id: "risk_webhook_replay_hardening",
    category: "git",
    title: "Webhook replay and GitHub App hardening are incomplete",
    severity: "high",
    likelihood: "medium",
    impact: "Webhook processing could be harder to operate safely under production traffic.",
    mitigation: "Plan GitHub App auth, delivery replay protection, idempotency, and rate-limit handling.",
    owner: "integrations",
    status: "deferred",
    metadata: { recommendedNextTask: true }
  }
];
