import test from "node:test";
import assert from "node:assert/strict";
import { getDashboardData } from "../apps/web/lib/mock-data.ts";
import { renderDashboardHtml } from "../apps/web/src/render.ts";

test("dashboard data exposes conflict manager v1 simulation and registry package assumptions", async () => {
  const data = await getDashboardData();

  assert.equal(data.activeLeases.length, 2);
  assert.equal(data.conflictRisks.length, 1);
  assert.equal(data.mergeQueue.length, 2);
  assert.equal(data.mergeSimulations.length, 2);
  assert.equal(data.registryOverview.activeSkills, 3);
  assert.equal(data.registryOverview.activeHarnesses, 3);
  assert.equal(data.registryOverview.activeInstructions, 3);
  assert.equal(Array.isArray(data.registryAuditLogs), true);
  assert.equal(data.registryApprovalQueue.some((item) => item.targetName === "auth-debugging"), true);
  assert.equal(data.registryRevisions.length >= 2, true);
  assert.equal(data.registryEvalResults.some((result) => result.evalName === "mock harness smoke"), true);
  assert.equal(data.registryPackages.some((manifest) => manifest.packageKind === "bundle"), true);
  assert.equal(data.registryVersionResolution.name, "jest-test-fixer");
  assert.equal(data.registryVersionResolution.selected?.version, "1.0.0");
  assert.equal(data.registryPackageDiff.summary.includes("changed"), true);
  assert.equal(data.mergeQueue.every((entry) => entry.simulationStatus === "clean"), true);
  assert.equal(data.mergeQueue.some((entry) => entry.recommendation === "manual_review_required"), true);
  assert.equal(data.taskRuns.every((run) => (run.selectedSkillRefs?.length ?? 0) > 0), true);
  assert.equal(data.taskRuns.every((run) => run.selectedHarnessRef !== undefined), true);
  assert.equal(data.improvementFailureSignals.length, 2);
  assert.equal(data.improvementFailureClusters.length, 1);
  assert.equal(data.improvementCandidates.some((candidate) => candidate.status === "proposal_created"), true);
  assert.equal(data.improvementProposals.some((proposal) => proposal.status === "eval_required"), true);
  assert.equal(data.evalRequirements.some((requirement) => requirement.blocking), true);
  assert.equal(data.canaryRolloutPlans.some((plan) => plan.status === "draft"), true);
  assert.equal(data.autoImprovementSafetyPolicies[0]?.allowAutoApply, false);
  assert.equal(data.autoImprovementAnalyses.some((analysis) => analysis.recommendedCandidateType === "update_instruction"), true);
  assert.equal(data.draftRegistryChanges.some((change) => change.status === "draft" && change.draftPayload.activeRegistryMutation === false), true);
  assert.equal(data.proposalReadiness[0]?.blockingReasons.includes("auto_apply_disabled"), true);
  assert.equal(data.proposalReviewQueue.length, 1);
  assert.equal(data.governanceDecisions.some((decision) => decision.decision === "mark_eval_required"), true);
  assert.equal(data.proposalEvalRuns.some((run) => run.status === "pending"), true);
  assert.equal(data.canaryReadiness[0]?.blockingReasons.includes("canary_required"), true);
  assert.equal(data.proposalApplyGates[0]?.blockingReasons.includes("active_apply_not_implemented"), true);
  assert.equal(data.governanceAuditEvents.some((event) => event.action === "proposal_apply_blocked"), true);
  assert.equal(data.gitProviderConfig.providerKind, "mock");
  assert.equal(data.gitProviderConfig.remoteGitEnabled, false);
  assert.equal(data.gitProviderConfig.githubConfigured, false);
  assert.equal(data.gitProviderConfig.githubAllowedBranchPrefix, "ai/");
  assert.equal(data.gitProviderConfig.githubAllowedRepoCount, 0);
  assert.equal(data.gitProviders.some((provider) => provider.providerKind === "github" && provider.remote === true && provider.enabled === false), true);
  assert.equal(data.gitBranches.some((branch) => branch.branchName === "codex/fix-login-timeout"), true);
  assert.equal(data.gitPullRequests.some((pullRequest) => pullRequest.url?.startsWith("mock://pull-requests/")), true);
  assert.equal(data.gitChangedFiles.some((file) => file.path === "src/auth/session.ts"), true);
  assert.equal(data.gitMergeQueueLinkage.some((link) => link.recommendation === "manual_review_required"), true);
  assert.equal(data.gitAuditEvents.some((event) => event.action === "git.branch_create_requested"), true);
  assert.equal(data.gitRemoteAuditEvents.some((event) => event.action === "git.github_branch_create_blocked"), true);
  assert.equal(data.remoteBlockedOperation.ok, false);
  assert.equal(data.remoteBlockedOperation.reason, "remote_git_disabled");
  assert.equal(data.remoteBranchBlockedOperation.ok, false);
  assert.equal(data.remoteBranchBlockedOperation.reason, "remote_git_disabled");
  assert.equal(data.llmProviderConfig.providerKind, "mock");
  assert.equal(data.llmProviderConfig.remoteLlmEnabled, false);
  assert.equal(data.llmModels.some((model) => model.id === "mock-registry-reviewer@1.0"), true);
  assert.equal(data.virtualModelKeys.some((key) => key.id === "vmk_system_mock"), true);
  assert.equal(data.llmCompletion?.ok, true);
  assert.equal(data.llmUsageEvents.some((event) => event.metadata?.source === "llm_gateway"), true);
  assert.equal(data.llmAuditEvents.some((event) => event.eventType === "llm_completion_succeeded"), true);
  assert.equal(data.remoteLlmBlockedOperation.ok, false);
  assert.equal(data.remoteLlmBlockedOperation.reason, "blocked_remote_llm_disabled");
  assert.equal(data.agentRunnerConfig.runnerKind, "mock");
  assert.equal(data.agentRunnerConfig.localRunnerEnabled, false);
  assert.equal(data.agentRunners.some((runner) => runner.runnerKind === "local" && runner.enabled === false), true);
  assert.equal(data.agentRun?.status, "completed");
  assert.equal(data.agentRun?.changedFiles.some((file) => file === "src/auth/session.ts"), true);
  assert.equal(data.agentRunAuditEvents.some((event) => event.eventType === "agent_run_completed"), true);
  assert.equal(data.agentInstructionAssemblies[0]?.instructionSetHash.startsWith("sha256:"), true);
  assert.equal(data.agentExecutors.some((executor) => executor.executorKind === "blocked" && executor.enabled === true), true);
  assert.equal(data.blockedCommandExample?.status, "blocked");
  assert.equal(data.agentCommandResults.some((result) => result.blockedReason === "Command execution requires explicit local execution, harness, and workspace gates."), true);
  assert.equal(data.localRunnerBlockedExample.reason, undefined);
  assert.equal(data.policyConfig.engineKind, "static");
  assert.equal(data.policyConfig.auditEnabled, true);
  assert.equal(data.policyRules.some((rule) => rule.id === "policy_improvement_apply_deny"), true);
  assert.equal(data.policyDecisions.some((decision) => decision.action === "llm.completion" && decision.allowed), true);
  assert.equal(data.policyDecisions.some((decision) => decision.action === "git.remote_operation" && !decision.allowed), true);
  assert.equal(data.policyDecisions.some((decision) => decision.action === "improvement.apply" && !decision.allowed), true);
  assert.equal(data.policyAuditEntries.some((entry) => entry.action === "runner.command.execute"), true);
  assert.equal(data.securityConfig.secretManagerKind, "mock");
  assert.equal(data.secretRefs.some((ref) => ref.provider === "mock"), true);
  assert.equal(data.secretScopes.some((scope) => scope.requiresApproval), true);
  assert.equal(data.secretLeaseRequest.status, "denied");
  assert.equal(data.sandboxProfiles.some((profile) => profile.kind === "local_temp_workspace" && profile.allowNetwork === false), true);
  assert.equal(data.sandboxDecision.allowed, true);
  assert.equal(data.networkPolicies[0]?.defaultAction, "deny");
  assert.equal(data.redactionPolicies[0]?.id, "redaction_default");
  assert.equal(data.redactionTest.redactedText.includes("sk-dashboard-secret"), false);
  assert.equal(data.securityAuditEvents.some((event) => event.eventType === "network_egress_blocked"), true);
  assert.equal(data.localAgentProtocolConfig.status, "available");
  assert.equal(data.localAgentProtocolConfig.mockTransportEnabled, true);
  assert.equal(data.localAgentProtocolConfig.fixtureDaemonSupportEnabled, true);
  assert.equal(data.localAgentProtocolConfig.mockChannelSupportEnabled, true);
  assert.equal(data.localAgentProtocolConfig.realTransportEnabled, false);
  assert.equal(data.localAgentProtocolConfig.vendorCliExecutionEnabled, false);
  assert.equal(data.localAgentProtocolConfig.activeMockChannels >= 1, true);
  assert.equal(data.localAgentRegistrations.some((agent) => agent.status === "connected"), true);
  assert.equal(data.localAgentChannels.some((channel) => channel.status === "established" && channel.handshakeStatus === "mock_verified"), true);
  assert.equal(data.localAgentHandshakes.some((handshake) => handshake.responseStatus === "mock_valid"), true);
  assert.equal(data.localAgentCapabilityAdvertisements.some((advertisement) => advertisement.supportsStreaming && advertisement.supportsCancellation), true);
  assert.equal(data.localAgentCompatibilityEntries.some((entry) => entry.providerTemplateId === "codex-cli-jsonl" && entry.supported), true);
  assert.equal(data.localAgentCompatibilityResults.some((result) => result.compatible && result.providerId === "codex-cli-local"), true);
  assert.equal(data.localAgentConsentRequests.some((request) => request.consentLevel === "read_only"), true);
  assert.equal(data.localAgentConsentDecision.decision, "approved_once");
  assert.equal(data.localAgentInvocation?.state, "completed");
  assert.equal(data.localAgentEvents.some((event) => event.source === "stdout"), true);
  assert.equal(data.localAgentStream?.state, "completed");
  assert.equal(data.localAgentStreamEvents.some((event) => event.source === "stderr" && event.type === "progress"), true);
  assert.equal(data.localAgentStreamEvents.every((event, index) => event.sequence === index + 1), true);
  assert.equal(data.localAgentAuditEvents.some((event) => event.eventType === "local_cli_direct_execution_blocked"), true);
  assert.equal(data.localAgentAuditEvents.some((event) => event.eventType === "credential_cache_access_denied"), true);
  assert.equal(data.providerAbstractionConfig.status, "available");
  assert.equal(data.providerCatalog.some((provider) => provider.id === "claude-code-local" && provider.kind === "local_cli"), true);
  assert.equal(data.providerAuthTypes.includes("external_cli_session"), true);
  assert.equal(data.providerLocalCliTemplates.some((template) => template.id === "codex-cli-jsonl"), true);
  assert.equal(data.providerValidation.ok, true);
  assert.equal(data.providerInvocation.status, "awaiting_consent");
  assert.equal(data.providerInvocation.error?.code, "awaiting_consent");
  assert.equal(data.providerAuditEvents.some((event) => event.eventType === "awaiting_consent"), true);
});

test("dashboard data preserves pending approval exclusion during registry version resolution", async () => {
  const data = await getDashboardData();

  assert.equal(data.pendingApprovalVersionResolution.name, "auth-debugging");
  assert.equal(data.pendingApprovalVersionResolution.selected, undefined);
  assert.equal(
    data.pendingApprovalVersionResolution.warnings.includes("skill auth-debugging@1.0.0 excluded: approvalStatus is pending."),
    true
  );
  assert.equal(
    data.pendingApprovalVersionResolution.errors.includes("No selectable skill version satisfies auth-debugging@^1.0.0."),
    true
  );
});

test("rendered dashboard shows dry-run merge simulation status, queue recommendation, and registry data", async () => {
  const html = await renderDashboardHtml();

  assert.equal(html.includes("Dry-run Merge Simulations"), true);
  assert.equal(html.includes("safe_to_queue"), true);
  assert.equal(html.includes("manual_review_required"), true);
  assert.equal(html.includes("clean"), true);
  assert.equal(html.includes("Registry selection"), true);
  assert.equal(html.includes("auth-debugging"), true);
  assert.equal(html.includes("backend-node20"), true);
  assert.equal(html.includes("org-secure-coding-baseline"), true);
  assert.equal(html.includes("approval approved"), true);
  assert.equal(html.includes("checksum unverified"), true);
  assert.equal(html.includes("Registry Audit"), true);
  assert.equal(html.includes("Approval Queue"), true);
  assert.equal(html.includes("rollback is available through the API"), true);
  assert.equal(html.includes("Mock harness smoke eval passed."), true);
  assert.equal(html.includes("Registry Packages"), true);
  assert.equal(html.includes("Version resolution"), true);
  assert.equal(html.includes("Package diff"), true);
  assert.equal(html.includes("Phase 4 Preparation"), true);
  assert.equal(html.includes("Failure signals"), true);
  assert.equal(html.includes("Improvement proposals"), true);
  assert.equal(html.includes("no auto-apply path exists"), true);
  assert.equal(html.includes("Auto-improvement analyses"), true);
  assert.equal(html.includes("Draft registry changes"), true);
  assert.equal(html.includes("auto_apply_disabled"), true);
  assert.equal(html.includes("Safety policy"), true);
  assert.equal(html.includes("Phase 4 Governance"), true);
  assert.equal(html.includes("Review queue"), true);
  assert.equal(html.includes("Apply gate"), true);
  assert.equal(html.includes("apply is not implemented"), true);
  assert.equal(html.includes("Git Adapter"), true);
  assert.equal(html.includes("remote Git disabled"), true);
  assert.equal(html.includes("GitHub gates"), true);
  assert.equal(html.includes("allowed repos 0"), true);
  assert.equal(html.includes("prefix ai/"), true);
  assert.equal(html.includes("codex/fix-login-timeout"), true);
  assert.equal(html.includes("src/auth/session.ts:modified"), true);
  assert.equal(html.includes("git.branch_create_requested"), true);
  assert.equal(html.includes("git.github_branch_create_blocked"), true);
  assert.equal(html.includes("remote_git_disabled"), true);
  assert.equal(html.includes("LLM Gateway"), true);
  assert.equal(html.includes("remote LLM disabled"), true);
  assert.equal(html.includes("mock-registry-reviewer@1.0"), true);
  assert.equal(html.includes("vmk_system_mock"), true);
  assert.equal(html.includes("llm_completion_succeeded"), true);
  assert.equal(html.includes("blocked_remote_llm_disabled"), true);
  assert.equal(html.includes("Agent Runner"), true);
  assert.equal(html.includes("local runner disabled"), true);
  assert.equal(html.includes("command execution disabled"), true);
  assert.equal(html.includes("Command executor"), true);
  assert.equal(html.includes("Blocked command example"), true);
  assert.equal(html.includes("Command execution requires explicit local execution, harness, and workspace gates."), true);
  assert.equal(html.includes("Workspace status"), true);
  assert.equal(html.includes("Latest agent run"), true);
  assert.equal(html.includes("Instruction assembly"), true);
  assert.equal(html.includes("Local runner blocked example"), true);
  assert.equal(html.includes("Policy-as-code"), true);
  assert.equal(html.includes("Policy engine"), true);
  assert.equal(html.includes("remote Git denied"), true);
  assert.equal(html.includes("policy_improvement_apply_deny"), true);
  assert.equal(html.includes("Secrets and Sandbox"), true);
  assert.equal(html.includes("Secret manager"), true);
  assert.equal(html.includes("Sandbox profiles"), true);
  assert.equal(html.includes("Network egress policy"), true);
  assert.equal(html.includes("Redaction policy"), true);
  assert.equal(html.includes("credential cache paths redacted"), true);
  assert.equal(html.includes("Local Agent Protocol"), true);
  assert.equal(html.includes("Protocol status"), true);
  assert.equal(html.includes("mock transport enabled"), true);
  assert.equal(html.includes("fixture daemon enabled"), true);
  assert.equal(html.includes("mock channel enabled"), true);
  assert.equal(html.includes("real transport disabled"), true);
  assert.equal(html.includes("vendor CLI execution disabled"), true);
  assert.equal(html.includes("Channels"), true);
  assert.equal(html.includes("mock_verified"), true);
  assert.equal(html.includes("Compatibility matrix"), true);
  assert.equal(html.includes("codex-cli-jsonl"), true);
  assert.equal(html.includes("Consent history"), true);
  assert.equal(html.includes("approved_once"), true);
  assert.equal(html.includes("Stream events"), true);
  assert.equal(html.includes("local_cli_direct_execution_blocked"), true);
  assert.equal(html.includes("credential_cache_access_denied"), true);
  assert.equal(html.includes("Enterprise LLM Providers"), true);
  assert.equal(html.includes("Provider abstraction"), true);
  assert.equal(html.includes("local_cli"), true);
  assert.equal(html.includes("Local Agent required"), true);
  assert.equal(html.includes("Credential cache access"), true);
  assert.equal(html.includes("PTY fallback"), true);
});
